version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "ci/cd"
      - "dependencies"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps): "

  - package-ecosystem: "uv"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
